### ISSUE TITLE
Changer les icones "élève" et "prof"

### ISSUE THREAD

**Issue by PierreTrovero** [AltEtude/backlog#19]
Le petit chapeau de diplômé serait plus pour l'élève. Il faudrait un icone adapté pour le prof.

**Comment by acorbel** [comment]
icones dispo: https://material.io/tools/icons/

**Comment by PierreTrovero** [comment]
tu ne peux utiliser que ceux là ?

**Comment by PierreTrovero** [comment]
ya le "work" et le "class" qui peuvent convenir

**Comment by acorbel** [comment]
c'est ceux du material design globalement. C'est directement incorporé ds ma librairie

**Comment by PierreTrovero** [comment]
Ok. Si tu peux mettre le chapeau au student et le work au prof c'est top
